version: '3.8'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-verification_system}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME:-verification-system}
      - SERVER_HOST=${SERVER_HOST:-http://localhost}
      - PROJECT_NAME=${PROJECT_NAME:-Verification System}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-["http://localhost:8000","http://localhost:3000"]}
      # Logging settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
volumes:
  postgres_data: