version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME:-verification-system}
      - SERVER_HOST=${SERVER_HOST:-http://localhost}
      - PROJECT_NAME=${PROJECT_NAME:-Verification System}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-["http://localhost:8000","http://localhost:3000"]}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}