version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verification_system
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_NAME=verification-system
      - SERVER_HOST=http://localhost
      - PROJECT_NAME=Verification System
      - BACKEND_CORS_ORIGINS=["http://localhost:8000","http://localhost:3000"]
      # Main PostgreSQL Database settings
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=verification_system
      # External MySQL Database settings (replace with actual values)
      - EXTERNAL_DB_HOST=${EXTERNAL_DB_HOST}
      - EXTERNAL_DB_PORT=${EXTERNAL_DB_PORT:-3306}
      - EXTERNAL_DB_USER=${EXTERNAL_DB_USER}
      - EXTERNAL_DB_PASSWORD=${EXTERNAL_DB_PASSWORD}
      - EXTERNAL_DB_NAME=${EXTERNAL_DB_NAME}
      # Security settings
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      # First admin user settings
      - FIRST_ADMIN_EMAIL=${FIRST_ADMIN_EMAIL:-admin@example.com}
      - FIRST_ADMIN_PASSWORD=${FIRST_ADMIN_PASSWORD:-admin-password}
      # AWS Bedrock settings
      - AWS_REGION=${AWS_REGION:-us-west-2}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # External API settings
      - PERSONA_API_KEY=${PERSONA_API_KEY}
      - SIFT_API_KEY=${SIFT_API_KEY}
      # Logging settings
      - LOG_LEVEL=INFO

volumes:
  postgres_data: